Further refinements

diff --git a/start b/start
--- a/start
+++ b/start
@@ -4,14 +4,11 @@
 mkdir -p /home/nzbget/maindir/
 mkdir -p /home/.config/rclone/
 
-curl -s $TEGBZN_CONF_URL -o /home/nzbget/nzbget.conf && 
-echo 'nzbget config loaded' || echo 'ERROR: unable to get nzbget config'
+curl  $TEGBZN_CONF_URL > /home/nzbget/nzbget.conf && 
+echo 'nzbget config loaded' || { echo 'ERROR: unable to get nzbget config' ; exit 1; }
 
-curl -s $RCONF_URL -o /home/.config/rclone/rclone.conf && 
-echo 'rclone config loaded' || echo 'ERROR: unable to get rclone config'
-
-echo 'List of remotes, the first remote shall be used for uploading stuff:'
-rclone listremotes
+curl  $RCONF_URL > /home/.config/rclone/rclone.conf && 
+echo 'rclone config loaded' || { echo 'ERROR: unable to get rclone config' ; exit 1; }
 
 # Rewrites certain options in nzbget.conf:
 sed -i \
@@ -25,14 +22,17 @@ sed -i \
 
 ./nzbget/nzbget -o ControlPort=$PORT -D
 
+echo 'List of remotes, the first remote shall be used for uploading stuff:'
+rclone listremotes
+
 # The ping file is used to decide when and when not to ping:
 echo '' > /home/ping.true
 
 # Extracts the extension of ping file, extension will always be a boolean value:
 ping=$(ls | grep '^ping' | awk -F. '{print$2}')
 
-# doa is the ping decider script and it is called at every 29 mins (from boot):
-while $ping; do sleep 1740; python3 doa.py ping_check; done
+# doa is the ping decider script and it is called at every 30 mins (from boot):
+while $ping; do sleep 1799; python3 doa.py ping_check; done
 
 # Shuts down nzbget when $ping is false:
 python3 doa.py shutdown
